package uk.gov.companieshouse.chs.gov.uk.notify.integration.api.restapi;

import static uk.gov.companieshouse.chs.gov.uk.notify.integration.api.ChsGovUkNotifyIntegrationService.APPLICATION_NAMESPACE;

import jakarta.validation.ValidationException;
import java.util.List;
import java.util.Map;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;
import org.thymeleaf.exceptions.TemplateInputException;
import uk.gov.companieshouse.chs.gov.uk.notify.integration.api.exception.SvgImageException;
import uk.gov.companieshouse.logging.Logger;
import uk.gov.companieshouse.logging.util.DataMap;

@ControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

    /**
     * Map of message (part) substitutions to make message more meaningful to human readers.
     * Workaround for fact we probably cannot provide a more meaningful message in
     * the @Pattern annotation in code generated by OpenAPI Generator.
     */
    private static final Map<String, String>
            ERROR_MESSAGE_PARAMETER_NAME_SUBSTITUTIONS =
            Map.of("sendLetter.arg1", "context ID (X-Request-ID)");

    /** Given this name to avoid any confusion with `ResponseEntityExceptionHandler.logger`. **/
    private final Logger myLogger;

    public GlobalExceptionHandler(Logger logger) {
        this.myLogger = logger;
    }

    /**
     * Returns HTTP Status 400 Bad Request when there is an exception implying that
     * the incoming request content is invalid.
     *
     * @param ve exception thrown when input from request is found to be invalid
     * @return response with payload reporting underlying cause
     */
    @ExceptionHandler(ValidationException.class)
    public ResponseEntity<Object> handleValidationException(
            ValidationException ve) {
        var message = "Error in " + APPLICATION_NAMESPACE + ": "
                + buildMessage(ve.getMessage());
        myLogger.error("Will handle error `" + message + "` by responding with 400 Bad Request.",
                getLogMap(message));
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(message);
    }

    /**
     * Returns HTTP Status 500 Internal Server Error when there is a TemplateInputException
     * implying that a template resource cannot be found. It does not return a 404 Not Found
     * response because this scenario represents a configuration error as the template lookup
     * must already have found context validation set up for the template identified in the
     * request. Possible underlying problems include the template itself cannot be found in the
     * assets, or a file the template refers to cannot be found in the assets.
     *
     * @param tie exception thrown when there is a fundamental problem with the template the engine
     *            has been directed to process
     * @return response with payload reporting underlying cause
     */
    @ExceptionHandler(TemplateInputException.class)
    public ResponseEntity<Object> handleTemplateInputException(
            TemplateInputException tie) {
        return reportInternalServerError(tie);
    }

    /**
     * Returns HTTP Status 500 Internal Server Error when there is an SvgImageException
     * implying that an SVG resource cannot be found. It does not return a 404 Not Found
     * response because this scenario represents a configuration error.
     *
     * @param sie exception thrown when an SVG resource cannot be found
     * @return response with payload reporting underlying cause
     */
    @ExceptionHandler(SvgImageException.class)
    public ResponseEntity<Object> handleSvgImageException(
            SvgImageException sie) {
        return reportInternalServerError(sie);
    }

    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(
            @NonNull MethodArgumentNotValidException manve,
            @NonNull HttpHeaders headers,
            @NonNull HttpStatusCode status,
            @NonNull WebRequest request) {
        if (manve.hasFieldErrors()) {
            var errors = manve.getFieldErrors().stream()
                    .map(this::buildMessage)
                    .sorted()
                    .toList();
            var message = "Error(s) in " + APPLICATION_NAMESPACE + ": " + errors;
            myLogger.error(message, getLogMap(errors));
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(message);
        }

        return super.handleMethodArgumentNotValid(manve, headers, status, request);
    }

    /**
     * Returns HTTP Status 500 Internal Server Error for the runtime exception provided.
     *
     * @param re An exception suggesting a programming or configuration error has arisen
     * @return HttpStatus.INTERNAL_SERVER_ERROR
     */
    private ResponseEntity<Object> reportInternalServerError(RuntimeException re) {
        var message = "Error in " + APPLICATION_NAMESPACE + ": "
                + buildMessage(re.getMessage() + " [cause: " + re.getCause() + "]");
        myLogger.error("Will handle error `" + message
                        + "` by responding with 500 Internal Server Error.",
                getLogMap(message));
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(message);
    }

    /**
     * Provides a more legible/meaningful substitution for part of a message originating from a
     * low level exception.
     * 
     * @param exceptionMessage the message provided by the intercepted exception
     * @return the sanitised version of the message
     */
    private String buildMessage(String exceptionMessage) {
        var newMessage = exceptionMessage;
        for (Map.Entry<String, String> entry :
                ERROR_MESSAGE_PARAMETER_NAME_SUBSTITUTIONS.entrySet()) {
            newMessage = newMessage.replace(entry.getKey(), entry.getValue());
        }
        return newMessage;
    }

    /**
     * Builds an intelligible error message from the {@link FieldError} provided.
     * @param fieldError the error to be reported
     * @return the error message
     */
    private String buildMessage(FieldError fieldError) {
        return fieldError.getObjectName() + " "
                + fieldError.getField() + " "
                + fieldError.getDefaultMessage();
    }

    private Map<String, Object> getLogMap(String error) {
        return new DataMap.Builder()
                .errorMessage(error)
                .build()
                .getLogMap();
    }

    private Map<String, Object> getLogMap(List<String> errors) {
        return new DataMap.Builder()
                .errors(errors)
                .build()
                .getLogMap();
    }

}
