spring.data.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.auto-index-creation=true

# This allows us to see the queries that are executed against the database for the view letter endpoints.
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Actuator health check config
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=/gov-uk-notify-integration/healthcheck
management.endpoint.health.enabled=true

gov.uk.notify.api.key=${CHS_GOV_UK_NOTIFY_INTEGRATION_API_KEY}

chs.notification.aws.s3-endpoint=s3://aws.s3.${AWS_REGION:eu-west-2}.amazonaws.com
chs.notification.aws.bucket-name=notification-attachments
chs.notification.aws.region=${AWS_REGION:eu-west-2}
chs.notification.aws.access-key-id=${AWS_ACCESS_KEY_ID}
chs.notification.aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
chs.notification.aws.path-style-access-enabled=false
